### ISSUE TITLE
Error with Array Collection

### ISSUE THREAD

**Issue by PauuloG** [PUGX/PUGXAutoCompleterBundle#34]
Hello,

I'm encountering an error I am unable to understand. My form contains this line 
```
->add('contacts', 'PUGX\AutocompleterBundle\Form\Type\AutocompleteType', array('class' => 'AppBundle:Client'))
```

And both controllers and routes are set as seen in documentation for search controllers (search and get). 

I receive this error when calling the route : 
````
Attempted to call an undefined method named "getId" of class "Doctrine\Common\Collections\ArrayCollection".
```

I don't really understand what's wrong.

**Comment by garak** [comment]
Hard to help, without more code

**Comment by PauuloG** [comment]
Autocomplete controller : 
```
    public function searchClientsAction(Request $request)
    {
        $q = $request->query->get('q');
        $results = $this->getDoctrine()->getRepository('AppBundle:Client')->findLikeName($q);

        return $this->render('autocomplete.html.twig', array('results' => $results));
    }

    public function getClientAction($id = null)
    {
        $client = $this->getDoctrine()->getRepository('AppBundle:Client')->findOneById($id);

        return new Response($client->getName());
    }
```

Client Entity Mapping 
```
AppBundle\Entity\Client:
    type: entity
    table: client
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        date_ajout:
            type: datetime
        date_modification:
            type: datetime
        name:
            type: string
            length: 100
        first_name:
            type: string
            length: 100
        type:
            type: integer
        societe:
            type: string
            length: 100
        slug:
            type: string
            length: 255
        provenance:
            type: integer
    oneToMany:
        infos:
            targetEntity: AppBundle\Entity\ContactInfo
            mappedBy: client
            cascade: ["persist", "remove"]
    manyToMany:
        dossiers:
            targetEntity: AppBundle\Entity\Dossier
            mappedBy: contacts
            cascade: ["persist"]
        dossiers_revendeur:
            targetEntity: AppBundle\Entity\Dossier
            mappedBy: revendeurs
            cascade: ["persist"]
```

Thanks for helping !
